plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/workspace/iris_64a73e71-5b95-4b9d-9dd6-7a6006e40c0d/deployables/china_wear_map_public"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]